version: '3.9'

services:
  database: 
    image: 'postgres'
    platform: linux/x86_64
    container_name: anamnesr
    restart: always
    environment:
      PGPASSWORD: '${PG_PASSWORD:-secret}'
      POSTGRES_DB: '${PG_DB_NAME}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD:-secret}'
      PG_HOST: '${PG_HOST}'
    ports:
      - '${PG_PORT:-5432}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', '${PG_DB_NAME}', '-U', '${PG_USER}']
      retries: 3
      timeout: 5s

volumes:
  pgdata: